name: init
description: Initialize bitrise __config (bitrise.yml)__ and __secrets (.bitrise.secrets.yml)__
  based on your project.
executable:
  osx: https://github.com/bitrise-io/bitrise-plugins-init/releases/download/1.11.1/bitrise-plugins-init-Darwin-x86_64
  osx-arm64: https://github.com/bitrise-io/bitrise-plugins-init/releases/download/1.11.1/bitrise-plugins-init-Darwin-arm64
  linux: https://github.com/bitrise-io/bitrise-plugins-init/releases/download/1.11.1/bitrise-plugins-init-Linux-x86_64
trigger: ""
requirements:
- tool: bitrise
  min_version: 1.41.1
  max_version: ""
